Repository lukso-network/docs, pull requests merged in 2024-07, with the labels that each got.

#1077 Add Nethermind to supported clients list
  docs/faq/network/network-configuration.md
  docs/faq/network/node-setup.md
  docs/networks/mainnet/running-a-node.md
Labels: documentation

#1080 feat: Add informaton about besu and teku integration
  docs/networks/mainnet/running-a-node.md
Labels: documentation

#1081 Update mainnet "running a node" page
  docs/networks/mainnet/running-a-node.md
Labels: bug, documentation, enhancement

#1085 Update mainnet "running a node" page
  docs/networks/mainnet/running-a-node.md
Labels: bug

#1092 feat: besu docs
  docs/faq/network/network-configuration.md
  docs/faq/network/node-setup.md
  docs/networks/mainnet/running-a-node.md
Labels: documentation

#1102 feat: Update client versions table
  docs/networks/mainnet/running-a-node.md
Labels: documentation
